/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se;

import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashutosh
 */
public class f3 extends javax.swing.JFrame {

    /**
     * Creates new form f3
     */
    static String s3 ;
    public f3() {
        initComponents();
        this.setSize(800, 500);
        this.setLocationRelativeTo(null) ;
        this.setResizable(false);
        l9.setCursor(new Cursor(Cursor.HAND_CURSOR));
        l10.setCursor(new Cursor(Cursor.HAND_CURSOR));
        goWebsite(l9);
        goWebsite(l10);
    }
    private void goWebsite(JLabel website) {
        website.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    if(website == l9)
                    {    
                        Desktop.getDesktop().browse(new URI("https://www.facebook.com/WhaleVision/"));
                    }
                    else if(website == l10)
                    {
                        Desktop.getDesktop().browse(new URI("https://twitter.com/WhaleVision"));
                    }    
                } catch (URISyntaxException | IOException ex) {
                    //It looks like there's a problem
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        pa2 = new javax.swing.JPasswordField();
        b5 = new javax.swing.JButton();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        l7.setFont(new java.awt.Font("Minion Pro Med", 0, 24)); // NOI18N
        l7.setText("USERNAME");
        getContentPane().add(l7);
        l7.setBounds(200, 150, 139, 50);

        l8.setFont(new java.awt.Font("Minion Pro Med", 0, 24)); // NOI18N
        l8.setText("PASSWORD");
        getContentPane().add(l8);
        l8.setBounds(200, 210, 139, 50);
        getContentPane().add(t5);
        t5.setBounds(400, 150, 203, 46);

        pa2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pa2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pa2KeyTyped(evt);
            }
        });
        getContentPane().add(pa2);
        pa2.setBounds(400, 210, 203, 43);

        b5.setFont(new java.awt.Font("Minion Pro Med", 0, 24)); // NOI18N
        b5.setText("LOGIN");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        b5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                b5KeyPressed(evt);
            }
        });
        getContentPane().add(b5);
        b5.setBounds(330, 300, 139, 54);

        l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/like-us-on-facebook-button.png"))); // NOI18N
        l9.setText("jLabel2");
        getContentPane().add(l9);
        l9.setBounds(160, 380, 190, 50);

        l10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/followusontwitterlogo.jpg"))); // NOI18N
        l10.setText("jLabel1");
        getContentPane().add(l10);
        l10.setBounds(450, 380, 200, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/hyfh.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        try 
        {
            String s1 = t5.getText() ;
            String s2 = new String(pa2.getPassword());
            ResultSet rs = DBConnect.st.executeQuery("select * from login where username = '"+s1+"'and password = '"+s2+"'");
            if(rs.next())
            {
                s3 = rs.getString(1) ;
                new f4().setVisible(true);
                this.dispose();
            }    
            else
            {
                pa2.setText("");
                JOptionPane.showMessageDialog(null, "Invalid Username/Password ! Please try Again. ");
            }    
        } 
        catch (Exception ex) 
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_b5KeyPressed

    private void pa2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pa2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pa2KeyPressed

    private void pa2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pa2KeyTyped

    }//GEN-LAST:event_pa2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f3().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b5;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JPasswordField pa2;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
