/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashutosh
 */
public class f5 extends javax.swing.JFrame {

    /**
     * Creates new form f5
     */
    public f5() {
        initComponents();
        this.setSize(811, 479);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cb2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cb3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel1.setText("Choose Course 1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(163, 158, 137, 25);

        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Introduction to Programming", "Data Structures", "Operating Systems", "Design and Analysis of Algorithms", "Principles of Programming Languages", "Software Engineering", "Theory of Computation", "VIL", "LIT", "Art of Numbers", " " }));
        getContentPane().add(cb1);
        cb1.setBounds(410, 158, 205, 25);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel2.setText("Choose Course 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(163, 201, 137, 28);

        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Introduction to Programming", "Data Structures", "Operating Systems", "Design and Analysis of Algorithms", "Principles of Programming Languages", "Software Engineering", "Theory of Computation", "MacroEconomics", "VIL", "LIT", "Art of Numbers", " " }));
        getContentPane().add(cb2);
        cb2.setBounds(410, 201, 205, 28);

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jLabel3.setText("Choose Course 3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(163, 247, 137, 28);

        cb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Introduction to Programming", "Data Structures", "Operating Systems", "Design and Analysis of Algorithms", "Principles of Programming Languages", "Software Engineering", "Theory of Computation", "MacroEconomics", "VIL", "LIT", "Art of Numbers", " " }));
        getContentPane().add(cb3);
        cb3.setBounds(410, 250, 205, 28);

        jButton1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 18)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(218, 333, 110, 40);

        jButton2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 333, 110, 40);

        jLabel4.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        jLabel4.setText("CHOOSE YOUR COURSES");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 20, 370, 60);

        jButton3.setText("LOGOUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(703, 10, 80, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/Blurred-Background1.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try 
        {
            int i = 100,j = 100,k = 100 ;
            String s1 = cb1.getSelectedItem().toString() ;
            String s2 = cb2.getSelectedItem().toString() ;
            String s3 = cb3.getSelectedItem().toString() ;        
            String s4 = f3.s3 ;
            String s5 = Integer.toString(i) ;
            String s6 = Integer.toString(j) ;
            String s7 = Integer.toString(k) ;
            DBConnect.st.executeQuery("insert into courses values('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+s5+"','"+s6+"','"+s7+"')") ;
            JOptionPane.showMessageDialog(null, "Your selected courses have been added.");
        } 
        catch (SQLException ex) {
            Logger.getLogger(f5.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        new f3().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cb3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
