/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se;

/**
 *
 * @author Ashutosh
 */
public class f6 extends javax.swing.JFrame {

    /**
     * Creates new form f6
     */
    public f6() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(811, 390);
        this.setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jt1.setBackground(new java.awt.Color(204, 255, 204));
        jt1.setBorder(new javax.swing.border.MatteBorder(null));
        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"CSD203", "Design and Analysis of Algorithms", "5", "4", "Dr.Debopam Acharya"},
                {"CSD304", "Theory of Computation", "3", "3", "Mr.Rajeev Kumar Singh"},
                {"CSD303", "Software Engineering", "3", "3", "Dr.Snigdha Biswas"},
                {"CCC803", "Art of Numbers", "3", "2", "Dr.SatyaNarayan Reddy"},
                {"CSD101", "Introduction to Programming", "5", "4", "Mr.JeyPrakash Chelladurai"},
                {"CSD201", "Data Structures", "5", "3", "Mrs.Richa Sharma"},
                {"CSD202", "Operating Systems", "5", "4", "Dr.Shashi Prabh"},
                {"CSD204", "Principles of Progamming Languages", "5", "4", "Dr.Dolly Sharma"},
                {"CSD801", "VIL", "3", "2", "Mr.GouriPrasanna Roy"},
                {"CCC303", "LIT", "3", "2", "Mr.Pramesh Ratnakar"}
            },
            new String [] {
                "Course Code", "Course", "Time", "Credits", "Faculty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jt1.setGridColor(new java.awt.Color(102, 255, 0));
        jScrollPane1.setViewportView(jt1);
        if (jt1.getColumnModel().getColumnCount() > 0) {
            jt1.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 759, 227);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(336, 312, 107, 37);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/calm-gaussian_00332693.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f6().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt1;
    // End of variables declaration//GEN-END:variables
}
